function UlRxPhyStats = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ULRXPHYSTATS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  ULRXPHYSTATS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Mar-2020 16:50:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["time", "cellId", "IMSI", "RNTI", "layer", "mcs", "size", "rv", "ndi", "correct", "ccId"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
UlRxPhyStats = readtable(filename, opts);

end
